
CREATE TABLE `biblioteca`.`livros` (
  `TITULO` VARCHAR(100) NOT NULL,
  `DATA_PUBLICACAO` DATE NOT NULL,
  `PAGINAS` VARCHAR(10) NOT NULL,
  `IDIOMA` VARCHAR(20) NOT NULL,
  `ISBN` VARCHAR(10) NOT NULL,
  `AUTORES` INT NOT NULL,
  `EDITORA` INT NOT NULL,
  PRIMARY KEY (`ISBN`));
  
CREATE TABLE `biblioteca`.`autores` (
  `NOME` VARCHAR(100) NOT NULL,
  `SOBRENOME` VARCHAR(100) NOT NULL,
  `DATA_NASCIMENTO` DATE,
  `ID_AUTOR` INT AUTO_INCREMENT,
  PRIMARY KEY(`ID_AUTOR`));

CREATE TABLE `biblioteca`.`editoras` (
  `NOME` VARCHAR(50) NOT NULL,
  `DATA_FUNDACAO` DATE NOT NULL,
  `ID_EDITORA` INT AUTO_INCREMENT,
  PRIMARY KEY(`ID_EDITORA`));

CREATE TABLE `biblioteca`.`usuarios` (
  `NOME` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `TELEFONE` VARCHAR(9) DEFAULT NULL,
  PRIMARY KEY (`CPF`));
  
  CREATE TABLE `biblioteca`.`emprestimos` (
  `LIVRO` VARCHAR(10) NOT NULL,
  `USUARIO` VARCHAR(11) NOT NULL,
  `DATA_RETIRADA` DATE NOT NULL,
  `QUANTIDADE_DIAS` INT NOT NULL,
  `STATUS_DEVOLUCAO` BIT NOT NULL,
  `ID_EMPRESTIMO` INT AUTO_INCREMENT,
  PRIMARY KEY(`ID_EMPRESTIMO`));
  
  /*
	Adicionando chaves estrangeiras
  */
  ALTER TABLE `biblioteca`.`livros` 
ADD INDEX `ID_AUTOR_idx` (`AUTORES` ASC) VISIBLE,
ADD INDEX `ID_EDITORA_idx` (`EDITORA` ASC) VISIBLE;
;
ALTER TABLE `biblioteca`.`livros` 
ADD CONSTRAINT `ID_AUTOR`
  FOREIGN KEY (`AUTORES`)
  REFERENCES `biblioteca`.`autores` (`ID_AUTOR`),
ADD CONSTRAINT `ID_EDITORA`
  FOREIGN KEY (`EDITORA`)
  REFERENCES `biblioteca`.`editoras` (`ID_EDITORA`);

  ALTER TABLE `biblioteca`.`emprestimos` 
ADD INDEX `ISBN_idx` (`LIVRO` ASC) VISIBLE;

ALTER TABLE `biblioteca`.`emprestimos` 
ADD CONSTRAINT `ISBN`
  FOREIGN KEY (`LIVRO`)
  REFERENCES `biblioteca`.`livros` (`ISBN`);
  
  ALTER TABLE `biblioteca`.`emprestimos` 
ADD INDEX `USUARIO_idx` (`USUARIO` ASC) VISIBLE;

ALTER TABLE `biblioteca`.`emprestimos` 
ADD CONSTRAINT `USUARIO`
  FOREIGN KEY (`USUARIO`)
  REFERENCES `biblioteca`.`usuarios` (`CPF`);
  
  
  
  

