USE biblioteca;

CREATE TABLE IF NOT EXISTS emprestimos_excluidos(
	ID_EMPRESTIMOS_EXCLUIDOS INT UNSIGNED AUTO_INCREMENT,
	LIVRO VARCHAR(100) NOT NULL,
    USUARIO VARCHAR(11) NOT NULL,
    DATA_RETIRADA DATE NOT NULL,
	QUANTIDADE_DIAS INT NOT NULL,
    DATA_DE_EXCLUSAO DATE NOT NULL,
    PRIMARY KEY (ID_EMPRESTIMOS_EXCLUIDOS)
);

DELIMITER //
CREATE TRIGGER TG_INSERT_DELETE_EMPRESTIMOS 
AFTER DELETE ON EMPRESTIMOS
	FOR EACH ROW INSERT EMPRESTIMOS_EXCLUIDOS 
	VALUES
	(DEFAULT, OLD.LIVRO, OLD.USUARIO, OLD.DATA_RETIRADA, OLD.QUANTIDADE_DIAS, NOW());

END//

DELETE FROM EMPRESTIMOS WHERE STATUS_DEVOLUCAO = 1;